### ISSUE TITLE
Broken link 

### ISSUE THREAD

**Issue by Sterling463** [rackerlabs/support-how-to#413] opened 2020-09-09 21:23 UTC
https://docs.rackspace.com/support/how-to/account-management

Bolded text is broken link

User management

- Account registration code
- Getting started with Role Based Access Control (RBAC)
- **Install AnyConnect**

**Comment by WilliamLoy** [comment] 2020-10-08 19:18
this is a duplicate of Issue 415

**Closed by WilliamLoy** 2020-10-08 19:18 UTC
